name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: chechout code
      uses: actions/checkout@v2
    -
      name: install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
          version: latest
    -
      name: Build the Docker image
      run: |
        docker buildx build . \
          --tag aero41/aeros-ulog:latest \
          --platform linux/amd64,linux/arm/v7
